### ISSUE TITLE
S2: rising lava in HT2 doesn't render

### ISSUE THREAD

**Issue by DanielOri** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#93]
https://user-images.githubusercontent.com/7793232/105418647-3a300f80-5c1c-11eb-9aa5-2a933e7b9017.mp4

**Comment by MGRich** [comment]
Fixed in latest build.

**Comment by DanielOri** [comment]
I am running the lastest release tho. Is it not fixed on prebuilt?

**Comment by breakthetargets** [comment]
> I am running the lastest release tho. Is it not fixed on prebuilt?

Latest release isn't actually the latest build. Go to the Actions tab to get the latest build for now.
